name: Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

  test:
    name: Test Job
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
