name: Deploy QA

on:
    workflow_run:
        workflows: [ Maven ]
        branches: [ main ]
        types:
            - completed

jobs:
    deploy_qa:
        name: Deploy QA
        runs-on: self-hosted
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            -   uses: actions/checkout@v4

            -   name: Download Artifact
                uses: dawidd6/action-download-artifact@v9
                with:
                    name: jar-artifact
                    path: tmp
                    workflow: Maven.yml
                    branch: main

            -   name: Stop the service
                run: ssh ${{ vars.QA_PATH }} "sudo kill \$(pgrep java)"
                continue-on-error: true

            -   name: Remove old jar
                run: ssh ${{ vars.QA_PATH }} "rm ~/Desktop/TwitchBot.jar"
                continue-on-error: true

            -   name: Copy Artifact
                run: scp tmp/TwitchBot.jar ${{ vars.QA_PATH }}:~/Desktop/TwitchBot.jar

            -   name: Start the service
                run: ssh ${{ vars.QA_PATH }} "sudo reboot"
                continue-on-error: true
