name: Deploy PROD

on:
    workflow_dispatch:

jobs:
    deploy_prod:
        name: Deploy PROD
        runs-on: self-hosted

        steps:
            -   name: Stop the service
                run: ssh ${{ vars.PROD_PATH }} "sudo kill \$(pgrep java)"
                continue-on-error: true

            -   name: Remove old jar
                run: ssh ${{ vars.PROD_PATH }} "rm -f ~/Desktop/TwitchBot.jar"

            -   name: Copy Artifact
                run: scp -3 ${{ vars.QA_PATH }}:~/Desktop/TwitchBot.jar ${{ vars.PROD_PATH }}:~/Desktop/TwitchBot.jar

            -   name: Start the service
                run: ssh ${{ vars.PROD_PATH }} "sudo reboot"
                continue-on-error: true
