name: Main Workflow

on:
    push:
        branches: [ main ]

jobs:
    build:
        name: Build Job
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/build

    test:
        name: Test Job
        runs-on: ubuntu-latest
        needs: build

        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/test

    deploy_qa:
        name: Deploy QA
        runs-on: self-hosted
        needs: [ build, test ]

        steps:
            -   uses: actions/checkout@v4

            -   name: Download Artifact
                uses: actions/download-artifact@v4
                with:
                    name: jar-artifact
                    path: tmp

            -   name: Stop the service
                run: ssh ${{ vars.QA_PATH }} "sudo kill \$(pgrep java)"
                continue-on-error: true

            -   name: Remove old jar
                run: ssh ${{ vars.QA_PATH }} "rm -f ~/Desktop/TwitchBot.jar"

            -   name: Copy Artifact
                run: scp tmp/TwitchBot.jar ${{ vars.QA_PATH }}:~/Desktop/TwitchBot.jar

            -   name: Start the service
                run: ssh ${{ vars.QA_PATH }} "sudo reboot"
                continue-on-error: true
