name: Maven

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: Build Job
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven

            -   name: Build Maven
                run: mvn -DskipTests clean install

            -   name: Upload Artifact
                uses: actions/upload-artifact@v4
                with:
                    name: jar-artifact
                    path: target/TwitchBot.jar
                    retention-days: 3

    test:
        name: Test Job
        runs-on: ubuntu-latest
        needs: build

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven

            -   name: Test maven
                run: mvn test
